const products=[
{id:1,name:"Galaxy S24",brand:"Samsung",cat:"Mobiles",icon:"📱",rating:4.6,spec:"8GB RAM • 256GB • 6.2-inch AMOLED",stores:[["Amazon",52999,"2 days"],["Flipkart",51999,"3 days"],["Croma",54490,"2 days"],["Reliance Digital",53999,"4 days"]],old:59999,history:[59999,57999,56999,54999,53999,52999,51999]},
{id:2,name:"iPhone 15",brand:"Apple",cat:"Mobiles",icon:"📱",rating:4.7,spec:"128GB • A16 Bionic • 6.1-inch OLED",stores:[["Amazon",61999,"2 days"],["Flipkart",62999,"2 days"],["Croma",64990,"3 days"],["Reliance Digital",63999,"4 days"]],old:69900,history:[69900,67999,66999,64999,63999,62999,61999]},
{id:3,name:"Pavilion 15",brand:"HP",cat:"Laptops",icon:"💻",rating:4.4,spec:"Core i5 • 16GB • 512GB SSD",stores:[["Amazon",58990,"2 days"],["Flipkart",57990,"3 days"],["Croma",60490,"3 days"],["Reliance Digital",59990,"4 days"]],old:67990,history:[67990,64990,63990,61990,60990,59990,57990]},
{id:4,name:"MacBook Air M2",brand:"Apple",cat:"Laptops",icon:"💻",rating:4.8,spec:"M2 • 8GB • 256GB SSD • 13.6-inch",stores:[["Amazon",82990,"2 days"],["Flipkart",84990,"3 days"],["Croma",87990,"2 days"],["Reliance Digital",86990,"4 days"]],old:99900,history:[99900,95990,92990,89990,86990,84990,82990]},
{id:5,name:"WH-1000XM5",brand:"Sony",cat:"Audio",icon:"🎧",rating:4.7,spec:"ANC • 30-hour battery • Bluetooth",stores:[["Amazon",27990,"1 day"],["Flipkart",28990,"2 days"],["Croma",29990,"2 days"],["Reliance Digital",29490,"3 days"]],old:34990,history:[34990,32990,31990,30990,29990,28990,27990]},
{id:6,name:"Airdopes 141",brand:"boAt",cat:"Audio",icon:"🎵",rating:4.2,spec:"42-hour playback • ENx • Type-C",stores:[["Amazon",1299,"1 day"],["Flipkart",1399,"2 days"],["Croma",1499,"3 days"],["Reliance Digital",1449,"3 days"]],old:4490,history:[4490,1999,1799,1599,1499,1399,1299]},
{id:7,name:"MX Keys Mini",brand:"Logitech",cat:"Accessories",icon:"⌨️",rating:4.5,spec:"Wireless • Backlit • Multi-device",stores:[["Amazon",7495,"2 days"],["Flipkart",7699,"3 days"],["Croma",7899,"2 days"],["Reliance Digital",7790,"4 days"]],old:8995,history:[8995,8499,8299,7999,7799,7699,7495]},
{id:8,name:"Mi Power Bank 4i",brand:"Xiaomi",cat:"Accessories",icon:"🔋",rating:4.3,spec:"20000mAh • 33W fast charging • USB-C",stores:[["Amazon",2199,"1 day"],["Flipkart",2299,"2 days"],["Croma",2399,"3 days"],["Reliance Digital",2249,"3 days"]],old:2999,history:[2999,2799,2599,2499,2399,2299,2199]}
];
const $=id=>document.getElementById(id),money=n=>"₹"+n.toLocaleString("en-IN"),low=p=>Math.min(...p.stores.map(x=>x[1])),high=p=>Math.max(...p.stores.map(x=>x[1])),disc=p=>Math.round((1-low(p)/p.old)*100);
let wish=JSON.parse(localStorage.getItem("pw_wish")||"[]"),priceChart,historyChart;

function card(p){return `<article class="product"><div class="pic">${p.icon}</div><div class="top"><span class="tag">${p.cat}</span><button class="heart ${wish.includes(p.id)?"on":""}" data-w="${p.id}">${wish.includes(p.id)?"♥":"♡"}</button></div><h3>${p.brand} ${p.name}</h3><div class="sub">${p.spec}</div><div class="price">${money(low(p))}<span class="old">${money(p.old)}</span><span class="discount">${disc(p)}% OFF</span></div><div class="rating">★ ${p.rating} • lowest across ${p.stores.length} stores</div><div class="actions"><button class="compare" data-c="${p.id}">Compare prices</button><button data-d="${p.id}">Details</button></div></article>`}
function render(){
 let q=$("search").value.toLowerCase(),cat=$("category").value,sort=$("sort").value;
 let a=products.filter(p=>(!q||`${p.name} ${p.brand} ${p.cat}`.toLowerCase().includes(q))&&(cat==="All"||p.cat===cat));
 if(sort==="low")a.sort((x,y)=>low(x)-low(y));if(sort==="high")a.sort((x,y)=>low(y)-low(x));if(sort==="discount")a.sort((x,y)=>disc(y)-disc(x));if(sort==="rating")a.sort((x,y)=>y.rating-x.rating);
 $("grid").innerHTML=a.map(card).join("");$("empty").classList.toggle("hide",a.length>0);$("clear").style.display=q?"block":"none";
 document.querySelectorAll("[data-w]").forEach(b=>b.onclick=()=>toggleWish(+b.dataset.w));document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>compare(+b.dataset.c));document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>details(+b.dataset.d));
}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];localStorage.setItem("pw_wish",JSON.stringify(wish));$("wishCount").textContent=wish.length;renderWishlist();render();toast(wish.includes(id)?"Added to wishlist":"Removed from wishlist")}
function fillSelects(){["chartProduct","historyProduct"].forEach(id=>$(id).innerHTML=products.map(p=>`<option value="${p.id}">${p.brand} ${p.name}</option>`).join(""))}
function updateChart(){let p=products.find(x=>x.id==$("chartProduct").value);if(priceChart)priceChart.destroy();priceChart=new Chart($("chart"),{type:"bar",data:{labels:p.stores.map(x=>x[0]),datasets:[{data:p.stores.map(x=>x[1]),backgroundColor:"#6869e7",borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>"₹"+Number(v).toLocaleString("en-IN")}},x:{grid:{display:false}}}}});deal(p)}
function updateHistory(){let p=products.find(x=>x.id==$("historyProduct").value);if(historyChart)historyChart.destroy();historyChart=new Chart($("historyChart"),{type:"line",data:{labels:["6 months ago","5 months","4 months","3 months","2 months","Last month","Today"],datasets:[{label:"Demo price",data:p.history,borderColor:"#5b5ce2",backgroundColor:"#5b5ce233",fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>"₹"+Number(v).toLocaleString("en-IN")}},x:{grid:{display:false}}}}})}
function deal(p){let b=p.stores.reduce((x,y)=>x[1]<y[1]?x:y),saving=high(p)-b[1];$("deal").innerHTML=`<div class="dealbox"><div style="font-size:45px">${p.icon}</div><h3>${p.brand} ${p.name}</h3><div class="big">${money(b[1])}</div><div class="saving">Potential saving vs highest listed price: ${money(saving)}</div>${p.stores.map(s=>`<div class="store"><span>${s[0]}</span><strong class="${s[1]===b[1]?"best":""}">${money(s[1])}</strong></div>`).join("")}</div>`}
function compare(id){let p=products.find(x=>x.id===id),b=low(p);$("modalBody").innerHTML=`<small style="color:var(--primary);font-weight:800">STORE COMPARISON</small><h2>${p.icon} ${p.brand} ${p.name}</h2><p class="sub">${p.spec}</p><table class="compare"><tr><th>Store</th><th>Price</th><th>Delivery</th></tr>${p.stores.map(s=>`<tr><td>${s[0]}</td><td class="${s[1]===b?"best":""}">${money(s[1])}</td><td>${s[2]}</td></tr>`).join("")}</table><p><b>Lowest listed price: ${money(b)}</b></p>`;$("modal").classList.remove("hide")}
function details(id){let p=products.find(x=>x.id===id);$("modalBody").innerHTML=`<div style="font-size:60px">${p.icon}</div><small style="color:var(--primary);font-weight:800">${p.cat}</small><h2>${p.brand} ${p.name}</h2><p>${p.spec}</p><p>Rating: ★ <b>${p.rating}/5</b></p><p>Lowest listed demo price: <b>${money(low(p))}</b></p><button class="primary" onclick="compare(${p.id})">Compare stores</button>`;$("modal").classList.remove("hide")}
function renderWishlist(){let a=products.filter(p=>wish.includes(p.id));$("wishlist").innerHTML=a.length?a.map(p=>`<div class="wishitem">${p.icon}<strong>${p.brand} ${p.name}</strong><span>From ${money(low(p))}</span></div>`).join(""):`<p class="note">No saved products yet. Use ♡ on a product to add it.</p>`}
function toast(s){let t=$("toast");t.textContent=s;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),1800)}
function stats(){let best=products.reduce((a,b)=>low(a)<low(b)?a:b),avg=Math.round(products.reduce((s,p)=>s+disc(p),0)/products.length),max=Math.max(...products.map(p=>high(p)-low(p)));$("statProducts").textContent=products.length;$("statDiscount").textContent=avg+"%";$("statBest").textContent=money(low(best));$("heroSave").textContent=money(max)}
$("search").oninput=render;$("category").onchange=render;$("sort").onchange=render;$("clear").onclick=()=>{$("search").value="";render()};$("chartProduct").onchange=updateChart;$("historyProduct").onchange=updateHistory;$("explore").onclick=()=>document.getElementById("productsSection").scrollIntoView({behavior:"smooth"});
$("close").onclick=()=>$("modal").classList.add("hide");$("modal").onclick=e=>{if(e.target==$("modal"))$("modal").classList.add("hide")};
$("theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("pw_dark",document.body.classList.contains("dark")?"1":"0");$("theme").textContent=document.body.classList.contains("dark")?"☀":"☾"};
$("wishNav").onclick=()=>document.querySelector(".wishlist-grid").scrollIntoView({behavior:"smooth"});
if(localStorage.getItem("pw_dark")==="1"){document.body.classList.add("dark");$("theme").textContent="☀"}
fillSelects();stats();render();renderWishlist();$("wishCount").textContent=wish.length;updateChart();updateHistory();
